"""Add blacklisted_tokens table

Revision ID: 98768efbe349
Revises: 1d6a4a00d29a
Create Date: 2025-08-28 23:30:15.478887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98768efbe349'
down_revision = '1d6a4a00d29a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('blacklisted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('idx_blacklisted_expires', 'blacklisted_tokens', ['expires_at'], unique=False)
    op.create_index('idx_blacklisted_token', 'blacklisted_tokens', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_blacklisted_token', table_name='blacklisted_tokens')
    op.drop_index('idx_blacklisted_expires', table_name='blacklisted_tokens')
    op.drop_table('blacklisted_tokens')
    # ### end Alembic commands ###